import os
from typing import Dict, Any
from backend.models import Patient

MEDICAL_DISCLAIMER = (
    "DISCLAIMER: This summary is generated by MedLens strictly from provided structured records. "
    "This application does NOT provide medical diagnoses, treatment recommendations, or prescriptions. "
    "Always consult a licensed medical professional for clinical decision-making."
)

SUMMARY_SYSTEM_PROMPT = """
You are MedLens Summary Engine.
Summarize the patient's structured medical data strictly based on provided facts.

STRICT MEDICAL COMPLIANCE RULES:
1. State ONLY what is present in the reviewed documents and patient profile.
2. Highlight abnormal lab values (LOW or HIGH) strictly based on their source-provided reference ranges.
3. DO NOT offer a diagnosis.
4. DO NOT offer treatment advice, medication dosage adjustments, or clinical recommendations.
5. If information is missing or ambiguous, state "Not available in provided records."
6. Maintain neutral, cautious clinical phrasing (e.g., "The January report lists hemoglobin as 10.4 g/dL, which was below the source reference range of 12.0 - 15.5 g/dL.")
"""

def generate_patient_summary(patient: Patient) -> Dict[str, Any]:
    """
    Generates structured AI summary derived from patient records.
    Uses Gemini API if available, or deterministic safe rule-based summary builder.
    """
    total_docs = len(patient.documents)
    total_labs = len(patient.lab_results)
    abnormal_labs = [l for l in patient.lab_results if l.status in ["LOW", "HIGH"]]
    unresolved_conflicts = [c for c in patient.conflicts if c.status == "Unresolved"]
    
    api_key = os.getenv("GEMINI_API_KEY")
    if api_key and len(api_key.strip()) > 5:
        try:
            from google import genai
            client = genai.Client(api_key=api_key)
            
            summary_payload = {
                "patient_name": patient.display_name,
                "age": patient.age,
                "sex": patient.sex,
                "symptoms": patient.symptoms,
                "conditions": patient.conditions,
                "allergies": patient.allergies,
                "medications": patient.medications,
                "lab_results": [
                    {
                        "test": l.test_name,
                        "value": l.value,
                        "unit": l.unit,
                        "range": l.reference_range,
                        "status": l.status,
                        "date": l.test_date
                    } for l in patient.lab_results
                ],
                "conflicts": [c.description for c in unresolved_conflicts]
            }
            
            response = client.models.generate_content(
                model="gemini-2.5-flash",
                contents=f"{SUMMARY_SYSTEM_PROMPT}\n\nPATIENT DATA:\n{summary_payload}"
            )
            return {
                "summary_text": response.text.strip(),
                "disclaimer": MEDICAL_DISCLAIMER,
                "reviewed_items_count": total_docs + total_labs
            }
        except Exception as e:
            print(f"[Gemini Summary Notice] Fallback to rule engine: {e}")

    # Fallback Rule-Based Summary Generation (Deterministic & Medically Safe)
    summary_parts = []
    summary_parts.append(
        f"MedLens reviewed a total of {total_docs} document(s) and {total_labs} laboratory test result(s) "
        f"for patient {patient.display_name} ({patient.age or 'N/A'} yrs, {patient.sex or 'N/A'})."
    )

    if patient.symptoms or patient.conditions:
        cond_list = ", ".join([c.get("name", "") for c in (patient.conditions or []) if c.get("name")])
        sym_list = ", ".join([s.get("name", "") for s in (patient.symptoms or []) if s.get("name")])
        summary_parts.append(
            f"Documented patient intake notes active conditions: [{cond_list or 'None documented'}] "
            f"and reported symptoms: [{sym_list or 'None reported'}]."
        )

    if abnormal_labs:
        ab_lines = [
            f"• {l.test_name}: {l.value} {l.unit or ''} (Status: {l.status}, Source Range: {l.reference_range or 'Not provided'}, Date: {l.test_date or 'N/A'})"
            for l in abnormal_labs
        ]
        summary_parts.append("Abnormal Laboratory Findings (Based on Source Reference Ranges):\n" + "\n".join(ab_lines))
    else:
        summary_parts.append("Laboratory Findings: All reviewed lab results fall within their respective source reference ranges or lack source reference ranges for comparison.")

    if unresolved_conflicts:
        c_lines = [f"• {c.conflict_type}: {c.description}" for c in unresolved_conflicts]
        summary_parts.append("Record Inconsistencies / Flagged Conflicts:\n" + "\n".join(c_lines))

    summary_parts.append("Missing Information: Documented clinical history not comprehensive. Further uploaded records may provide additional context.")

    return {
        "summary_text": "\n\n".join(summary_parts),
        "disclaimer": MEDICAL_DISCLAIMER,
        "reviewed_items_count": total_docs + total_labs
    }
